### ISSUE TITLE
Add ability to limit tests by test duration rather than the number of test iterations

### ISSUE THREAD

**Issue by vlsi** [jqwik-team/jqwik#336]
## Testing Problem

I'm testing database-related integration cases like "create table", "drop table", and the sequence of operations is generated on the fly (see #134), so `@Property(tries=42)` is not suitable for me as I have no idea how much time a single iteration would take.

## Suggested Solution

Support something like `@Timeout` from JUnit5: https://junit.org/junit5/docs/5.5.1/api/org/junit/jupiter/api/Timeout.html

The "test timeout" feature could be implemented via `AfterProperty` + `AroundTryHook`, however, having an out-of-the-box timeout would be perfect.

See https://www.fuzzingbook.org/html/WhenToStopFuzzing.html, https://docs.gitlab.com/ee/user/application_security/coverage_fuzzing/#duration-of-coverage-guided-fuzz-testing

**Comment by vlsi** [comment]
> @Property(tries = 10000, maxSeconds= 10) 

That makes sense, and I have pretty much the same intention: allow stop the test as soon as the first limit is exhausted.

As I started adding my own `@Timeout`, and I immediately realized I want to be able to pass the timeout from the command line (e.g to allow different CI jobs to have different fuzz durations).

I'm not sure what to do about it, and it might be that a generic "pass values from command line" (e.g. via system properties) might be helpful.

For instance, what if jqwik picks up `jqwilk.proprerty.com.acme.MyProperties.propertyName.tries=42` and uses that as an override for `@Property` on top of `propertyName` method in `com.acme.MyProperties` class?

**Comment by vlsi** [comment]
> This would make the most sense as a generic feature for all attributes accepted by @Property

I moved the discussion to #337

In any case, I think it would be fine to put timeout to `@Property(...)` (and `@PropertyDefaults`).

**Comment by vlsi** [comment]
Well, it is awesome there's `net.jqwik.api.lifecycle.TryExecutionResult#satisfied(shouldPropertyFinishEarly=true)` which would do exactly what I need for the timeout feature :)

**Comment by jlink** [comment]
This will be supported by jqwik 2. So I close the feature request for jqwik 1.

**Comment by vlsi** [comment]
Is there an issue tracker for jqwik 2?

**Comment by jlink** [comment]
Not yet, but there will be.
