### ISSUE TITLE
ListArbitrary<T> providers are not selected to resolve List<T> parameters

### ISSUE THREAD

**Issue by lmartelli** [jqwik-team/jqwik#485]
## Testing Problem

A `@Provide` method in a domain that returns a `ListArbitrary<Thing>` is not used to generate values for a `@ForAll List<Thing>`. See https://github.com/jqwik-team/jqwik/compare/main...lmartelli:jqwik:ListArbitrary-provider

## Suggested Solution

In `net.jqwik.engine.properties.DomainContextBaseProviders.MethodBasedArbitraryProvider#arbitraryType()` the actual generic type parameter of ListArbitrary<T> is lost when navigating to the implemented interface Arbitrary<T>. 

I am not sure if the mapping can be done in the general case, but it seems safe to say that in the case where there is only one generic type parameter in the class and in the interface, it can be propagated. 

I will try to do that.

**Comment by jlink** [comment]
@lmartelli I assume you haven't found a viable solution. Feel free to re-open if I'm wrong.
