### ISSUE TITLE
Mockito Support (includes link to working code)

### ISSUE THREAD

**Issue by agustafson-atl** [jqwik-team/jqwik#605]
## Testing Problem
It would be great if a jqwik test could integrate with Mockito as easily as JUnit does.

## Suggested Solution
I've put together the code for it here: https://github.com/agustafson-atl/jqwik-mockito/
I'm happy for it to be moved under the jqwik github account if possible. Otherwise I can move it to my company's account.

## Discussion
This would allow users to use jqwik in more situations, which would be great.

**Comment by jlink** [comment]
Worthwhile idea to scrutinise. But the link does not work: 404.

**Comment by agustafson-atl** [comment]
Ah it helps if I make the repository public! 🤦    I've made it public now and can confirm that it's now visible.
Thanks for taking a look so quickly @jlink  - appreciate it.

**Comment by jlink** [comment]
I wonder if it would make sense if the lifecycle hook would be symmetrical to Mockito‘s Jupiter extension - as far as possible. This would it easy for Jupiter users to reuse their knowledge. 
What do you think, @agustafson-atl ?

**Comment by agustafson-atl** [comment]
Thanks for the feedback @jlink but I'm not sure what that would mean practically? As in, we should allow user to add a `@ExtendsWith(MockitoLifecycleHooks.class)` annotation to their class instead of `@AddLifecycleHook(MockitoLifecycleHooks.class)`? Or you can see that there are gaps/differences between the `MockitoLifecycleHooks` and what Mockito's Jupiter extension provides?

Either way, I'm happy to make the transition simple for users to go from JUnit to jqwik. My hope was that we could just replace:
- `@ExtendsWith(MockitoLifecycleHooks.class)` with `@AddLifecycleHook(MockitoLifecycleHooks.class)`
- `@Test` with `@Example` or `@Property`
- `@Nested` with `@Group`
and things would "just work".

**Comment by jlink** [comment]
What I mean is that the jqwik hook should do the same things as the jupiter extension. If I understand your code correctly, all it does is reset mocks after each try, whereas the extension does more (eg initialise `@Mock` variables). But I may be missing something. 

Have you looked at the extension’s implementation? Most of the code should be in the hook as well.

**Comment by agustafson-atl** [comment]
Ah, ok I can take a look to see what the extension does - good idea thanks.

My code is currently initialising Mockito annotated elements on this line:
https://github.com/agustafson-atl/jqwik-mockito/blob/main/src/main/java/net/jqwik/mockito/MockitoLifecycleHooks.java#L65

I can take a look at the Mockito extension, but I've added test cases which include:
- fields instantiated explicitly, ie: `Mockito.mock` calls
- fields instantiated via annotations, ie: `@Mock` or `@InjectMocks`
- nested tests using `@Group`

I wanted to cover off any use cases that I knew about, and I think every case should be adequately covering them off.

**Comment by jlink** [comment]
And sorry for suggesting too many changes. If you think you're done, that's good with me. We can then consider moving it to @junit-team and making it an official extension.

**Comment by agustafson-atl** [comment]
I did wonder about the mocks potentially resetting per property or per try, but I couldn't realistically think of a reason why anybody would want to maintain state across multiple tries. But for completeness I imagine that would be an improvement.
I hadn't thought about the other concerns you'd raised. I'll take a look into them.

I hadn't considered to make it a JUnit extension as it's using jqwik and Mockito. But if you think that makes more sense then I can do that. Would I just replicate the issue in their repo and reference this issue?

Don't worry for suggesting the changes - appreciate it!

**Comment by jlink** [comment]
Not a JUnit extension. A jqwik extension. My wording was misleading.

**Comment by agustafson-atl** [comment]
Ok, gotcha. A jqwik extension makes sense.

I'll look into the issues you raised. Looking at the `MockitoExtension` I can see it has support for `@Strictness` as well, so I'll attempt to add some extra functionality based on the `MockitoExtension`.

I may have to get approval from my company to open-source this as they have a policy regarding contributions. Will update this issue once I've got more info and code is updated.

**Comment by agustafson-atl** [comment]
Hi, I've kicked off the open-sourcing process with my company and that should be approved soonish.

I've also updated/fixed the lib so that it uses a `Store` to keep track of mocks rather than storing them as a field. That should support parallelisation.

I also tried to work out how to cover the missing functionality that you raised, ie:
- Factory parameterisation
- Parameter resolution
But I couldn't work out what that involved after checking docs. Can you please give me some more feedback/ideas as to what to do, or where there are examples/docs? Alternatively we can add that functionality in a later release if it's non-trivial.

Thanks!

**Comment by agustafson-atl** [comment]
Ok, I've chatted to legal and they're happy for me to open-source the library.

For now I think we just ship the library as-is, and can add the extra functionality in the next release.

Thanks again @jlink for all the clear instructions of how to make those changes. I'll look to make them in a few weeks' time. The assistance you've given has really helped to make the open-sourcing process simple and relatively painless.

Let me know the next steps or if you require anything more from my end.

**Comment by jlink** [comment]
I'll set up the repo on @jqwik-team later today for you and give you access so that you can push your code.
Starting from there we can go through the publishing process.

Please keep in mind that I will add a license, code of conduct, and a `.editorconfig` file and set up the Gradle build process. You can modify the editor config to your liking if you really want, but I discourage you from changing more than a few minor things.

**Comment by jlink** [comment]
@agustafson-atl I invited you to https://github.com/jqwik-team/jqwik-mockito

Mind that everything I added during set up is up for discussion with the exception of `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md`.

**Comment by agustafson-atl** [comment]
Great, thanks for that @jlink - I'll try to find some time to transfer over the code. I'm happy with the default `.editorconfig`,  `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md`.

**Comment by agustafson-atl** [comment]
Ok, I've merged in my code and updated the gradle build scripts to Kotlin.

Will be great to go through the publishing process and get something out there.

**Comment by jlink** [comment]
I fixed publishing and published it as `0.0.1-SNAPSHOT`. You can try this out.

**Comment by jlink** [comment]
@agustafson-atl Some open questions/issues that should be tackled before first release:
- The current code formatting is not consistent with .editorconfig (which does a * import in all cases). 
  Either format accordingly or change it in .editorconfig
- Version `0.0.1` is not ambitious enough IMO. I'd go with `0.5`, `0.9` or even `1.0.0` depending on your plans
- Maybe introducing an annotation like `@JqwikMockitoSupport` would be a more convenient public API than  the somewhat clumsy `@AddLifecycleHook(MockitoLifecycleHooks.class)`. What do you think?

**Comment by agustafson-atl** [comment]
Great! Thanks for fixing the publishing details. I've made one minor fix to the build script to fix a related issue: https://github.com/jqwik-team/jqwik-mockito/commit/f20022f9bff9367a11dc085c0de9682809d77971

I've updated the version to 1.0.0-SNAPSHOT as I'd agree that we've probably got enough to release v1.0.0.

I've updated that the `*.gradle.kts` scripts are included in `.editorconfig` and reformatted too, as well as reformatting all of the files. I've removed the spotless plugin which was reformatting code as it was overriding the editorconfig.

I'm ok with `@AddLifecycleHook(MockitoLifecycleHooks.class)` because it lines up with `@ExtendsWith(MockitoExtension.class)`, but we can add a single annotation as that might make things a bit cleaner and simpler.

**Comment by jlink** [comment]
So maybe renaming `MockitoLifecycleHooks` to `JqwikMockitoExtension` would make it even more similar?

BTW, I published `1.0.0-SNAPSHOT`.

**Comment by agustafson-atl** [comment]
I think I'm happy with the code as it is, so perhaps we should publish the v1.0.0 release? Do I have permission to do that, or would you prefer to be in charge of that @jlink?

**Comment by jlink** [comment]
As far as I‘m aware the required user token for sonatype‘s Maven Central cannot be restricted to just one library. I use a single token for all jqwik modules. Moreover, signing the artefacts requires a private key. So I suggest that I release the module when you tell me so. At least that’s how it works with all the other jqwik extension modules.

**Comment by vlsi** [comment]
Sonatype tokens could be restricted to groupid, so you could ask them to allow the needed userid to be able to publish to org.jqwik.extensions.mockito groupid. WDYT?

**Comment by vlsi** [comment]
On the other hand, releasing everything together is viable as well, however, it might be easier to use monorepo it that case rather than multiple git repos

**Comment by jlink** [comment]
I’ll have a look at it. Do you have a link to the documentation for that @vlsi ? My search did not bring it up.
Will do the first release anyway. The extension modules have a different lifecycle and versioning scheme since they are maintained by different people.

**Comment by vlsi** [comment]
Previously one could file a JIRA to allow users a,b,c to publish under groupid of your choice.
Currently, it looks like JIRA has been decommission, so the solution probably is contact the support `central-support at sonatype.com` and ask them to allow certain userids to publish under a subgroup.

**Comment by vlsi** [comment]
By the way, it looks like migrating to Central Portal is not worth as [it does not currently support SNAPSHOTs](https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/), and it has a different publishing workflow, so Gradle plugins might not be up to speed.

**Comment by jlink** [comment]
> By the way, it looks like migrating to Central Portal is not worth as [it does not currently support SNAPSHOTs](https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/), and it has a different publishing workflow, so Gradle plugins might not be up to speed.

Publishing to Maven Central is getting more and more involved. I get that Sonatype provide the service for free, but still...

**Comment by jlink** [comment]
I released `1.0.0` and will therefore close this issue.

Let's do all further discussion directly within https://github.com/jqwik-team/jqwik-mockito.

**Comment by agustafson-atl** [comment]
I'm happy for you to do the releases if you're comfortable with that thanks @jlink. I'll have to think about how to create the changelog for any changes.
